### PR TITLE
Adding more build-in features by sensor

### PR DESCRIPTION
**Pull request by ipa-lth**
* The first commit solve the #36 issue by requesting the sensitivity from the sensor and using this to calibrate to SI units. 
* The second commit allows to define a (sensor internal) moving average filter at startup (According to the manuals) via rosparam:
1: Moving average point 1 point→ Response frequency 1000Hz 
2: Moving average point 2 points→ Response frequency 500Hz 
4: Moving average point 4 points→ Response frequency 250Hz 
8: Moving average point 8 points→ Response frequency 125Hz

### CODE REVIEW

**Comment by ipa-lth** [comment]
I tested it on a A6500 and will probably use it on a A6200

**Comment by k-okada** [comment]
Thank you for contribution!!!
Just out  of curiosity, this code will calibrate when the node startup, so for example, assuming extreme case, to start this node, we need to make sure that there is nothing on the sensor, and during the experiment, someone put the object on this sensor and the node measures the force.  If the node stops for some reason, and we restart them. Then the node publishes zero.
So avoid this solution, one possible solution is to store calibrate data into rospaarm and load them when startup, also enable to calibrate by service call (std_srv/Empty) may help. But this might be future work. I think this PR itself seems ok for me.

**Comment by ipa-lth** [comment]
Don't worry. The calibration is not "tare". It does not depend on the current load, but is (statically) stored on the sensor itself. As far as I know, wakoh will calibrate their sensor, store it and it will never be changed again (besides possible wakoh recalibration).
I included a rosparam "acquire_calibration". If you set this to false it will just behave like before this fix

**Comment by k-okada** [comment]
great , thanks.

**Pull request merged**
